@file:OptIn(kotlinx.serialization.ExperimentalSerializationApi::class)

package dev.shinsou.kmp.migration.shuyue

import kotlinx.serialization.SerializationException
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.decodeFromJsonElement
import kotlinx.serialization.json.intOrNull
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.longOrNull

/** Stable failure categories for strict ShuYue v1 input handling. */
public enum class ShuYueBackupV1ErrorCode {
    INPUT_TOO_LARGE,
    MALFORMED_JSON,
    UNSUPPORTED_VERSION,
    VALIDATION_FAILED,
    INVALID_LIMITS,
}

/**
 * A fail-closed decode error.  The message and path are generated by the host and never include
 * parser text, input snippets, script source, chapter text, or secret values.
 */
public class ShuYueBackupV1Exception(
    public val code: ShuYueBackupV1ErrorCode,
    override val message: String,
    public val path: String? = null,
    public val report: ShuYueMigrationValidationReport? = null,
) : IllegalArgumentException(message) {
    override fun toString(): String = buildString {
        append("ShuYueBackupV1Exception(code=").append(code)
        if (path != null) append(", path=").append(path)
        append(')')
    }
}

/**
 * Strict, bounded decoder for the legacy ShuYue JSON export.
 *
 * The raw DTO graph is internal on purpose: callers should consume [ShuYueBackupV1Stager.preview]
 * and its redacted report instead of receiving plaintext credentials/cookies or executable script
 * as a public application value.
 */
internal class ShuYueBackupV1Codec(
    private val limits: ShuYueBackupV1Limits = ShuYueBackupV1Limits.Default,
) {
    private val json: Json = Json {
        encodeDefaults = false
        explicitNulls = true
        ignoreUnknownKeys = false
        isLenient = false
        coerceInputValues = false
        allowTrailingComma = false
    }

    /** Decode only a supported, structurally valid v1 payload. */
    internal fun decode(encoded: String): ShuYueBackupV1 {
        validateConfiguredLimits()
        if (encoded.length > limits.maxRawChars) {
            throw ShuYueBackupV1Exception(
                ShuYueBackupV1ErrorCode.INPUT_TOO_LARGE,
                "The backup exceeds the configured character limit.",
                path = "root",
            )
        }
        val rawBytes = encoded.encodeToByteArray().size
        if (rawBytes > limits.maxRawBytes) {
            throw ShuYueBackupV1Exception(
                ShuYueBackupV1ErrorCode.INPUT_TOO_LARGE,
                "The backup exceeds the configured byte limit.",
                path = "root",
            )
        }
        return decodeText(encoded)
    }

    /**
     * Byte-oriented entry point for file/import adapters.  The byte cap is checked before UTF-8
     * decoding, so a hostile file cannot force a second full-size byte copy merely to be rejected.
     */
    internal fun decode(encoded: ByteArray): ShuYueBackupV1 {
        validateConfiguredLimits()
        if (encoded.size > limits.maxRawBytes) {
            throw ShuYueBackupV1Exception(
                ShuYueBackupV1ErrorCode.INPUT_TOO_LARGE,
                "The backup exceeds the configured byte limit.",
                path = "root",
            )
        }
        val text = try {
            encoded.decodeToString(throwOnInvalidSequence = true)
        } catch (_: Exception) {
            throw malformed("The backup is not valid UTF-8.", "root")
        }
        if (text.length > limits.maxRawChars) {
            throw ShuYueBackupV1Exception(
                ShuYueBackupV1ErrorCode.INPUT_TOO_LARGE,
                "The backup exceeds the configured character limit.",
                path = "root",
            )
        }
        return decodeText(text)
    }

    private fun decodeText(encoded: String): ShuYueBackupV1 {
        validateJsonGuards(encoded)

        val root = parseRoot(encoded)
        val versionElement = root["version"]
            ?: throw malformed("The backup version is required.", "version")
        val version = primitiveInt(versionElement)
            ?: throw malformed("The backup version is invalid.", "version")
        if (version != 1) {
            throw ShuYueBackupV1Exception(
                ShuYueBackupV1ErrorCode.UNSUPPORTED_VERSION,
                "The backup version is not supported.",
                path = "version",
            )
        }
        if (root["createdAt"] == null) {
            throw malformed("The backup creation time is required.", "createdAt")
        }
        if (primitiveLong(root["createdAt"]) == null) {
            throw malformed("The backup creation time is invalid.", "createdAt")
        }

        val backup = try {
            json.decodeFromJsonElement<ShuYueBackupV1>(root)
        } catch (_: SerializationException) {
            throw malformed("The backup JSON does not match the supported wire schema.", "root")
        } catch (_: IllegalArgumentException) {
            // Some serializers surface malformed primitive values as IllegalArgumentException.
            // Do not forward that parser text because it may include an input fragment.
            throw malformed("The backup JSON does not match the supported wire schema.", "root")
        }

        val report = ShuYueBackupV1Validator.validate(backup, limits)
        if (report.hasErrors) {
            throw ShuYueBackupV1Exception(
                ShuYueBackupV1ErrorCode.VALIDATION_FAILED,
                "The backup failed structural validation.",
                path = "root",
                report = report,
            )
        }
        return backup
    }

    private fun parseRoot(encoded: String): JsonObject {
        val element = try {
            json.parseToJsonElement(encoded)
        } catch (_: SerializationException) {
            throw malformed("The backup is not valid JSON.", "root")
        } catch (_: IllegalArgumentException) {
            throw malformed("The backup is not valid JSON.", "root")
        }
        return element as? JsonObject
            ?: throw malformed("The backup root must be a JSON object.", "root")
    }

    /** Lightweight lexical guard that runs before kotlinx.serialization builds a JSON tree. */
    private fun validateJsonGuards(encoded: String) {
        val containers = mutableListOf<JsonContainerGuard>()
        var totalMemberCount = 0
        var totalValueCount = 0
        var inString = false
        var escaped = false
        var stringStart = -1
        var previousSignificant: Char? = null

        fun registerValueStart() {
            if (totalValueCount >= limits.maxTotalJsonValues) {
                throw ShuYueBackupV1Exception(
                    ShuYueBackupV1ErrorCode.INPUT_TOO_LARGE,
                    "The backup JSON value count exceeds the configured limit.",
                    path = "root",
                )
            }
            val parent = containers.lastOrNull()
            if (parent?.opening == '[') {
                if (parent.arrayElementCount >= limits.maxJsonArrayElements) {
                    throw ShuYueBackupV1Exception(
                        ShuYueBackupV1ErrorCode.INPUT_TOO_LARGE,
                        "A backup JSON array exceeds the configured element limit.",
                        path = "root",
                    )
                }
                parent.arrayElementCount++
            }
            totalValueCount++
        }

        var index = 0
        while (index < encoded.length) {
            val character = encoded[index]
            if (inString) {
                if (escaped) {
                    escaped = false
                } else if (character == '\\') {
                    escaped = true
                } else if (character == '"') {
                    inString = false
                    var next = index + 1
                    while (next < encoded.length && encoded[next].isWhitespace()) next++
                    val memberNames = containers.lastOrNull()?.memberNames
                    if (next < encoded.length && encoded[next] == ':' && memberNames != null) {
                        val memberName = decodeJsonMemberName(encoded, stringStart + 1, index)
                        if (memberName in memberNames) {
                            throw malformed("A JSON object member is duplicated.", "root")
                        }
                        if (memberNames.size >= limits.maxJsonObjectMembers ||
                            totalMemberCount >= limits.maxTotalJsonMembers
                        ) {
                            throw ShuYueBackupV1Exception(
                                ShuYueBackupV1ErrorCode.INPUT_TOO_LARGE,
                                "The backup JSON member count exceeds the configured limit.",
                                path = "root",
                            )
                        }
                        memberNames += memberName
                        totalMemberCount++
                    } else {
                        registerValueStart()
                    }
                    previousSignificant = '"'
                }
                index++
                continue
            }
            when (character) {
                '"' -> {
                    inString = true
                    stringStart = index
                }
                '{' -> {
                    registerValueStart()
                    containers += JsonContainerGuard('{', linkedSetOf())
                    if (containers.size > limits.maxJsonDepth) {
                        throw ShuYueBackupV1Exception(
                            ShuYueBackupV1ErrorCode.INPUT_TOO_LARGE,
                            "The backup JSON nesting exceeds the configured limit.",
                            path = "root",
                        )
                    }
                }
                '[' -> {
                    registerValueStart()
                    containers += JsonContainerGuard('[', null)
                    if (containers.size > limits.maxJsonDepth) {
                        throw ShuYueBackupV1Exception(
                            ShuYueBackupV1ErrorCode.INPUT_TOO_LARGE,
                            "The backup JSON nesting exceeds the configured limit.",
                            path = "root",
                        )
                    }
                }
                '}' -> {
                    if (containers.lastOrNull()?.opening != '{') {
                        throw malformed("The backup JSON structure is invalid.", "root")
                    }
                    containers.removeAt(containers.lastIndex)
                }
                ']' -> {
                    if (containers.lastOrNull()?.opening != '[') {
                        throw malformed("The backup JSON structure is invalid.", "root")
                    }
                    containers.removeAt(containers.lastIndex)
                }
                '-', in '0'..'9', 't', 'f', 'n' -> {
                    if (previousSignificant == null ||
                        previousSignificant == '[' || previousSignificant == ',' || previousSignificant == ':'
                    ) {
                        registerValueStart()
                    }
                }
            }
            if (!character.isWhitespace()) previousSignificant = character
            index++
        }
        if (inString || escaped || containers.isNotEmpty()) {
            throw malformed("The backup JSON structure is invalid.", "root")
        }
    }

    /** Decode a member name so escaped and literal spellings share one duplicate-key identity. */
    private fun decodeJsonMemberName(encoded: String, startInclusive: Int, endExclusive: Int): String {
        val decoded = StringBuilder(minOf(endExclusive - startInclusive, 256))
        var index = startInclusive
        while (index < endExclusive) {
            val character = encoded[index++]
            if (character != '\\') {
                if (character.code < 0x20) {
                    throw malformed("A JSON object member name is invalid.", "root")
                }
                decoded.append(character)
            } else {
                if (index >= endExclusive) {
                    throw malformed("A JSON object member name is invalid.", "root")
                }
                when (val escape = encoded[index++]) {
                    '"', '\\', '/' -> decoded.append(escape)
                    'b' -> decoded.append('\b')
                    'f' -> decoded.append('\u000C')
                    'n' -> decoded.append('\n')
                    'r' -> decoded.append('\r')
                    't' -> decoded.append('\t')
                    'u' -> {
                        if (index + 4 > endExclusive) {
                            throw malformed("A JSON object member name is invalid.", "root")
                        }
                        var value = 0
                        repeat(4) {
                            val digit = hexDigitValueOrNull(encoded[index++])
                                ?: throw malformed("A JSON object member name is invalid.", "root")
                            value = (value shl 4) or digit
                        }
                        decoded.append(value.toChar())
                    }
                    else -> throw malformed("A JSON object member name is invalid.", "root")
                }
            }
            val maximumMemberNameChars = maxOf(
                limits.maxFieldChars,
                limits.maxIdentifierChars,
                limits.maxPreferenceFieldChars,
            )
            if (decoded.length > maximumMemberNameChars) {
                throw ShuYueBackupV1Exception(
                    ShuYueBackupV1ErrorCode.INPUT_TOO_LARGE,
                    "A JSON object member name exceeds the configured limit.",
                    path = "root",
                )
            }
        }
        return decoded.toString()
    }

    private fun hexDigitValueOrNull(character: Char): Int? = when (character) {
        in '0'..'9' -> character.code - '0'.code
        in 'a'..'f' -> character.code - 'a'.code + 10
        in 'A'..'F' -> character.code - 'A'.code + 10
        else -> null
    }

    private data class JsonContainerGuard(
        val opening: Char,
        val memberNames: MutableSet<String>?,
        var arrayElementCount: Int = 0,
    )

    private fun validateConfiguredLimits() {
        val invalid = listOf(
            limits.maxRawBytes,
            limits.maxRawChars,
            limits.maxJsonDepth,
            limits.maxJsonObjectMembers,
            limits.maxTotalJsonMembers,
            limits.maxJsonArrayElements,
            limits.maxTotalJsonValues,
            limits.maxBooks,
            limits.maxChapters,
            limits.maxChaptersPerBook,
            limits.maxChapterChars,
            limits.maxProgress,
            limits.maxIssues,
            limits.maxPreviewBooks,
            limits.maxPreviewChapters,
            limits.maxPreviewPlugins,
            limits.maxFieldChars,
            limits.maxIdentifierChars,
            limits.maxTitleChars,
            limits.maxDescriptionChars,
            limits.maxCategoryChars,
            limits.maxPluginFieldChars,
            limits.maxRepositoryFieldChars,
            limits.maxUrlChars,
            limits.maxInstalledPlugins,
            limits.maxPluginInstallations,
            limits.maxPluginSources,
            limits.maxTotalPluginSources,
            limits.maxRepositories,
            limits.maxRepositoryEntries,
            limits.maxRepositoryEntriesPerRepository,
            limits.maxPluginScriptBytes,
            limits.maxCredentials,
            limits.maxCookies,
            limits.maxPreferences,
            limits.maxImageParsingPolicies,
            limits.maxCredentialFieldChars,
            limits.maxCookieFieldChars,
            limits.maxPreferenceFieldChars,
        ).any { it < 0 }
        if (invalid || limits.maxTotalChapterChars < 0L || limits.maxTotalPluginScriptBytes < 0L) {
            throw ShuYueBackupV1Exception(
                ShuYueBackupV1ErrorCode.INVALID_LIMITS,
                "The configured backup limits are invalid.",
                path = "limits",
            )
        }
    }

    private fun malformed(message: String, path: String): ShuYueBackupV1Exception =
        ShuYueBackupV1Exception(ShuYueBackupV1ErrorCode.MALFORMED_JSON, message, path = path)

    private fun primitiveInt(element: kotlinx.serialization.json.JsonElement): Int? =
        runCatching { element.jsonPrimitive.intOrNull }.getOrNull()

    private fun primitiveLong(element: kotlinx.serialization.json.JsonElement?): Long? =
        element?.let { runCatching { it.jsonPrimitive.longOrNull }.getOrNull() }
}
